title: HF-ITCNE24-SemArbeit2-BPMN-Personalprozess
description: HF ITCNE24 2. Semesterarbeit zum Thema BPMN
theme: just-the-docs

url: https://Radball-Migi.github.io/HF-ITCNE24-Semarbeit2

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
